// Generated by gencpp from file vslam/position.msg
// DO NOT EDIT!


#ifndef VSLAM_MESSAGE_POSITION_H
#define VSLAM_MESSAGE_POSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace vslam
{
template <class ContainerAllocator>
struct position_
{
  typedef position_<ContainerAllocator> Type;

  position_()
    : angle(0.0)
    , p()  {
    }
  position_(const ContainerAllocator& _alloc)
    : angle(0.0)
    , p(_alloc)  {
  (void)_alloc;
    }



   typedef float _angle_type;
  _angle_type angle;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _p_type;
  _p_type p;





  typedef boost::shared_ptr< ::vslam::position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vslam::position_<ContainerAllocator> const> ConstPtr;

}; // struct position_

typedef ::vslam::position_<std::allocator<void> > position;

typedef boost::shared_ptr< ::vslam::position > positionPtr;
typedef boost::shared_ptr< ::vslam::position const> positionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vslam::position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vslam::position_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vslam

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'vslam': ['/home/lq/Documents/visual-odometry/src/vslam/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vslam::position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vslam::position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vslam::position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vslam::position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vslam::position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vslam::position_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vslam::position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b61d066c73d062e24b69a478e96849ce";
  }

  static const char* value(const ::vslam::position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb61d066c73d062e2ULL;
  static const uint64_t static_value2 = 0x4b69a478e96849ceULL;
};

template<class ContainerAllocator>
struct DataType< ::vslam::position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vslam/position";
  }

  static const char* value(const ::vslam::position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vslam::position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 angle\n\
geometry_msgs/Point p\n\
\n\
#是注释\n\
#使用geometry_msgs 需要在find_package和generate_messages添加geometry_msgs\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::vslam::position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vslam::position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
      stream.next(m.p);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vslam::position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vslam::position_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
    s << indent << "p: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.p);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VSLAM_MESSAGE_POSITION_H
